dashname = "Test"
theme = "theme"

[[widgets]]
id = 1
type = "display"
x = 2
y = 2
width = 24
height = 5
value = "Wi-Fi"

[[widgets]]
id = 2
type = "display"
x = 25
y = 2
width = 24
height = 5
value = "Bluetooth"
